=== matteofiorentino03/LWEB-Homework3/xml/attaccanti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="attaccanti">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="attaccante" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID_giocatore" type="xs:int"/>
              <xs:element name="gol_fatti" type="xs:int"/>
              <xs:element name="assist" type="xs:int"/>
              <xs:element name="ammonizioni" type="xs:int"/>
              <xs:element name="espulsioni" type="xs:int"/>
              <xs:element name="ruolo">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="punta"/>
                    <xs:enumeration value="seconda punta"/>
                    <xs:enumeration value="ala"/>
                    <xs:enumeration value="falso 9"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/attaccanti.xml
<?xml version="1.0" encoding="UTF-8"?>
<attaccanti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="attaccanti.xsd">
  <attaccante>
    <ID_giocatore>20</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>ala</ruolo>
  </attaccante>
  <attaccante>
    <ID_giocatore>22</ID_giocatore>
    <gol_fatti>1</gol_fatti>
    <assist>1</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>punta</ruolo>
  </attaccante>
  <attaccante>
    <ID_giocatore>23</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>seconda punta</ruolo>
  </attaccante>
  <attaccante>
    <ID_giocatore>24</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>punta</ruolo>
  </attaccante>
  <attaccante>
    <ID_giocatore>25</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>1</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>punta</ruolo>
  </attaccante>
</attaccanti>
