=== matteofiorentino03/LWEB-Homework3/xml/bonus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="TipoBonusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MagliaRetro"/>
      <xs:enumeration value="Reputazione"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="bonus">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="premio" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:int"/>
              <xs:element name="tipo" type="TipoBonusType"/>
              <xs:element name="descrizione" type="xs:string"/>
              <xs:element name="crediti" type="xs:decimal"/>
              <xs:element name="reputazioneMinima" type="xs:int" minOccurs="0"/>
              <xs:element name="limite_utilizzi" type="xs:integer" minOccurs="0"/>
              <xs:element name="stagione" type="xs:int" minOccurs="0"/>
              <xs:element name="data_inizio" type="xs:date" minOccurs="0"/>
              <xs:element name="attivo" type="xs:boolean"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/bonus.xml
<?xml version="1.0" encoding="UTF-8"?>
<bonus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bonus.xsd">
  <premio>
    <ID>1</ID>
    <tipo>MagliaRetro</tipo>
    <descrizione>Bonus di 15 crediti, se è una Maglia Retrò (delle scorse stagioni).</descrizione>
    <crediti>15</crediti>
    <attivo>true</attivo>
  </premio>
  <premio>
    <ID>2</ID>
    <tipo>Reputazione</tipo>
    <descrizione>Bonus di 33 crediti, se il Cliente ha una reputazione Alta ed è un fedelissimo.</descrizione>
    <crediti>33</crediti>
    <reputazioneMinima>69</reputazioneMinima>
    <limite_utilizzi>3</limite_utilizzi>
    <data_inizio>2023-10-15</data_inizio>
    <attivo>true</attivo>
  </premio>
</bonus>
