=== matteofiorentino03/LWEB-Homework3/xml/centrocampisti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="centrocampisti">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="centrocampista" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID_giocatore" type="xs:int"/>
              <xs:element name="gol_fatti" type="xs:int"/>
              <xs:element name="assist" type="xs:int"/>
              <xs:element name="ammonizioni" type="xs:int"/>
              <xs:element name="espulsioni" type="xs:int"/>
              <xs:element name="ruolo">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="mediano"/>
                    <xs:enumeration value="mezz ala"/>
                    <xs:enumeration value="trequartista"/>
                    <xs:enumeration value="centrale"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/centrocampisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<centrocampisti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="centrocampisti.xsd">
  <centrocampista>
    <ID_giocatore>14</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>1</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>mediano</ruolo>
  </centrocampista>
  <centrocampista>
    <ID_giocatore>15</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>1</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>centrale</ruolo>
  </centrocampista>
  <centrocampista>
    <ID_giocatore>16</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>centrale</ruolo>
  </centrocampista>
  <centrocampista>
    <ID_giocatore>17</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>mezz ala</ruolo>
  </centrocampista>
  <centrocampista>
    <ID_giocatore>18</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>trequartista</ruolo>
  </centrocampista>
  <centrocampista>
    <ID_giocatore>19</ID_giocatore>
    <gol_fatti>1</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>trequartista</ruolo>
  </centrocampista>
  <centrocampista>
    <ID_giocatore>26</ID_giocatore>
    <gol_fatti>2</gol_fatti>
    <assist>1</assist>
    <ammonizioni>1</ammonizioni>
    <espulsioni>1</espulsioni>
    <ruolo>centrale</ruolo>
  </centrocampista>
  <centrocampista>
    <ID_giocatore>26</ID_giocatore>
    <gol_fatti>1</gol_fatti>
    <assist>1</assist>
    <ammonizioni>1</ammonizioni>
    <espulsioni>1</espulsioni>
    <ruolo>mediano</ruolo>
  </centrocampista>
</centrocampisti>
