=== matteofiorentino03/LWEB-Homework3/xml/compra.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="compra">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ordine" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:int"/>
              <xs:element name="ID_Utente" type="xs:int"/>
              <xs:element name="ID_Maglia" type="xs:int"/>
              <xs:element name="pagamento_finale" type="xs:int"/>
              <xs:element name="indirizzo_consegna" type="xs:string"/>
              <xs:element name="data_compra" type="xs:date"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/compra.xml
<?xml version="1.0" encoding="UTF-8"?>
<compra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compra.xsd">
  <ordine>
    <ID>1</ID>
    <ID_Utente>2</ID_Utente>
    <ID_Maglia>9</ID_Maglia>
    <pagamento_finale>160</pagamento_finale>
    <indirizzo_consegna>Via l'etto</indirizzo_consegna>
    <data_compra>2025-09-22</data_compra>
  </ordine>
  <ordine>
    <ID>2</ID>
    <ID_Utente>2</ID_Utente>
    <ID_Maglia>10</ID_Maglia>
    <pagamento_finale>170</pagamento_finale>
    <indirizzo_consegna>Via l'etto</indirizzo_consegna>
    <data_compra>2025-09-22</data_compra>
  </ordine>
  <ordine>
    <ID>3</ID>
    <ID_Utente>2</ID_Utente>
    <ID_Maglia>3</ID_Maglia>
    <pagamento_finale>160</pagamento_finale>
    <indirizzo_consegna>Via l'etto</indirizzo_consegna>
    <data_compra>2025-09-22</data_compra>
  </ordine>
  <ordine>
    <ID>4</ID>
    <ID_Utente>2</ID_Utente>
    <ID_Maglia>2</ID_Maglia>
    <pagamento_finale>170</pagamento_finale>
    <indirizzo_consegna>Via l'etto</indirizzo_consegna>
    <data_compra>2025-09-22</data_compra>
  </ordine>
  <ordine>
    <ID>5</ID>
    <ID_Utente>3</ID_Utente>
    <ID_Maglia>7</ID_Maglia>
    <pagamento_finale>140</pagamento_finale>
    <indirizzo_consegna>Via carina</indirizzo_consegna>
    <data_compra>2025-09-22</data_compra>
  </ordine>
  <ordine>
    <ID>6</ID>
    <ID_Utente>4</ID_Utente>
    <ID_Maglia>43</ID_Maglia>
    <pagamento_finale>125</pagamento_finale>
    <indirizzo_consegna>via si</indirizzo_consegna>
    <data_compra>2025-09-23</data_compra>
  </ordine>
</compra>
