=== matteofiorentino03/LWEB-Homework3/xml/crediti_richieste.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="crediti_richieste">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="richiesta" maxOccurs="unbounded">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="ID" type="xs:int"/>
                <xs:element name="user_id" type="xs:int"/>
                <xs:element name="importo" type="xs:decimal"/>
                <xs:element name="stato">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                    <xs:enumeration value="In attesa"/>
                    <xs:enumeration value="Approvata"/>
                    <xs:enumeration value="Rifiutata"/>
                    </xs:restriction>
                </xs:simpleType>
                </xs:element>
                <xs:element name="created_at" type="xs:dateTime"/>
            </xs:sequence>
            </xs:complexType>
        </xs:element>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/crediti_richieste.xml
<?xml version="1.0" encoding="UTF-8"?>
<crediti_richieste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="crediti_richieste.xsd">
  <richiesta>
    <ID>1</ID>
    <user_id>2</user_id>
    <importo>100.50</importo>
    <stato>Approvata</stato>
    <created_at>2025-09-20T10:30:00</created_at>
  </richiesta>
  <richiesta>
    <ID>2</ID>
    <user_id>2</user_id>
    <importo>125.00</importo>
    <stato>Approvata</stato>
    <created_at>2025-09-22T18:25:35</created_at>
  </richiesta>
  <richiesta>
    <ID>3</ID>
    <user_id>2</user_id>
    <importo>13.00</importo>
    <stato>Rifiutata</stato>
    <created_at>2025-09-22T18:33:31</created_at>
  </richiesta>
  <richiesta>
    <ID>4</ID>
    <user_id>5</user_id>
    <importo>500.00</importo>
    <stato>Approvata</stato>
    <created_at>2025-10-20T18:24:09</created_at>
  </richiesta>
</crediti_richieste>
