=== matteofiorentino03/LWEB-Homework3/xml/difensori.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="difensori">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="difensore" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID_giocatore" type="xs:int"/>
              <xs:element name="gol_fatti" type="xs:int"/>
              <xs:element name="assist" type="xs:int"/>
              <xs:element name="ammonizioni" type="xs:int"/>
              <xs:element name="espulsioni" type="xs:int"/>
              <xs:element name="ruolo">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="centrale"/>
                    <xs:enumeration value="terzino"/>
                    <xs:enumeration value="braccetto"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/difensori.xml
<?xml version="1.0" encoding="UTF-8"?>
<difensori xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="difensori.xsd">
  <difensore>
    <ID_giocatore>5</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>1</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>centrale</ruolo>
  </difensore>
  <difensore>
    <ID_giocatore>6</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>centrale</ruolo>
  </difensore>
  <difensore>
    <ID_giocatore>7</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>centrale</ruolo>
  </difensore>
  <difensore>
    <ID_giocatore>8</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>centrale</ruolo>
  </difensore>
  <difensore>
    <ID_giocatore>9</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>terzino</ruolo>
  </difensore>
  <difensore>
    <ID_giocatore>11</ID_giocatore>
    <gol_fatti>1</gol_fatti>
    <assist>1</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>terzino</ruolo>
  </difensore>
  <difensore>
    <ID_giocatore>12</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>terzino</ruolo>
  </difensore>
  <difensore>
    <ID_giocatore>13</ID_giocatore>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
    <ruolo>braccetto</ruolo>
  </difensore>
</difensori>
