=== matteofiorentino03/LWEB-Homework3/xml/giocatori.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="giocatori">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="giocatore" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:int"/>
              <xs:element name="cf" type="xs:string"/>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="cognome" type="xs:string"/>
              <xs:element name="nazionalita" type="xs:string"/>
              <xs:element name="datanascita" type="xs:date"/>
              <xs:element name="num_maglia" type="xs:int"/>
              <xs:element name="altezza" type="xs:decimal"/>
              <xs:element name="market_value" type="xs:decimal"/>
              <xs:element name="presenze" type="xs:int"/>
              <xs:element name="cod_contratto" type="xs:string"/>
              <xs:element name="Tipo_Contratto">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="TRASFERIMENTO TEMPORANEO"/>
                    <xs:enumeration value="TRASFERIMENTO DEFINITIVO"/>
                    <xs:enumeration value="PROMOSSO DALLA PRIMAVERA"/>
                    <xs:enumeration value="RINNOVATO"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="stipendio" type="xs:decimal"/>
              <xs:element name="Data_inizio" type="xs:date"/>
              <xs:element name="Data_scadenza" type="xs:date"/>
              <xs:element name="ID_utenti" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/giocatori.xml
<?xml version="1.0" encoding="UTF-8"?>
<giocatori xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="giocatori.xsd">
  <giocatore>
    <ID>1</ID>
    <cf>M1L3SV1L4R</cf>
    <nome>Mile</nome>
    <cognome>Svilar</cognome>
    <nazionalita>Serbia - Belgio</nazionalita>
    <datanascita>1999-08-27</datanascita>
    <num_maglia>99</num_maglia>
    <altezza>1.89</altezza>
    <market_value>25000000.00</market_value>
    <presenze>3</presenze>
    <cod_contratto>SM0725</cod_contratto>
    <Tipo_Contratto>RINNOVATO</Tipo_Contratto>
    <stipendio>4360000.00</stipendio>
    <Data_inizio>2025-07-11</Data_inizio>
    <Data_scadenza>2030-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>2</ID>
    <cf>D3V4SQU3Z</cf>
    <nome>Devis</nome>
    <cognome>Vasquez</cognome>
    <nazionalita>Colombia</nazionalita>
    <datanascita>1998-05-12</datanascita>
    <num_maglia>32</num_maglia>
    <altezza>1.95</altezza>
    <market_value>2000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>VD0725</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>500000.00</stipendio>
    <Data_inizio>2025-07-29</Data_inizio>
    <Data_scadenza>2027-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>3</ID>
    <cf>P13RG0LL0</cf>
    <nome>Pierluigi</nome>
    <cognome>Gollini</cognome>
    <nazionalita>Italia</nazionalita>
    <datanascita>1995-03-18</datanascita>
    <num_maglia>95</num_maglia>
    <altezza>1.94</altezza>
    <market_value>100000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>GP0125</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>1480000.00</stipendio>
    <Data_inizio>2025-01-24</Data_inizio>
    <Data_scadenza>2027-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>4</ID>
    <cf>R4D0Z3LE3ZNY</cf>
    <nome>Radoslaw</nome>
    <cognome>Zelezny</cognome>
    <nazionalita>Polonia</nazionalita>
    <datanascita>2006-09-06</datanascita>
    <num_maglia>91</num_maglia>
    <altezza>1.93</altezza>
    <market_value>175000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>ZR0725</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>50000.00</stipendio>
    <Data_inizio>2025-07-23</Data_inizio>
    <Data_scadenza>2029-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>5</ID>
    <cf>ND1CK4</cf>
    <nome>Evan</nome>
    <cognome>Ndicka</cognome>
    <nazionalita>Costa d'Avorio - Francia</nazionalita>
    <datanascita>1999-08-20</datanascita>
    <num_maglia>5</num_maglia>
    <altezza>1.92</altezza>
    <market_value>30000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>NE0723</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>5130000.00</stipendio>
    <Data_inizio>2023-07-01</Data_inizio>
    <Data_scadenza>2028-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>6</ID>
    <cf>M4NC10</cf>
    <nome>Gianluca</nome>
    <cognome>Mancini</cognome>
    <nazionalita>Italia</nazionalita>
    <datanascita>1996-04-17</datanascita>
    <num_maglia>23</num_maglia>
    <altezza>1.90</altezza>
    <market_value>15000000.00</market_value>
    <presenze>1</presenze>
    <cod_contratto>MG0920</cod_contratto>
    <Tipo_Contratto>RINNOVATO</Tipo_Contratto>
    <stipendio>6480000.00</stipendio>
    <Data_inizio>2020-09-01</Data_inizio>
    <Data_scadenza>2027-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>7</ID>
    <cf>H3RM0S0N</cf>
    <nome>Mario</nome>
    <cognome>Hermoso</cognome>
    <nazionalita>Spagna</nazionalita>
    <datanascita>1995-06-18</datanascita>
    <num_maglia>22</num_maglia>
    <altezza>1.84</altezza>
    <market_value>7000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>HM0924</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>6480000.00</stipendio>
    <Data_inizio>2024-09-02</Data_inizio>
    <Data_scadenza>2027-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>8</ID>
    <cf>GH1L4RD0N3</cf>
    <nome>Daniele</nome>
    <cognome>Ghilardi</cognome>
    <nazionalita>Italia</nazionalita>
    <datanascita>2003-01-06</datanascita>
    <num_maglia>87</num_maglia>
    <altezza>1.89</altezza>
    <market_value>5000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>GD0825</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>1000000.00</stipendio>
    <Data_inizio>2025-08-02</Data_inizio>
    <Data_scadenza>2026-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>9</ID>
    <cf>ANG3L1N0</cf>
    <nome>José Angel</nome>
    <cognome>Esmoris (Angelino)</cognome>
    <nazionalita>Spagna</nazionalita>
    <datanascita>1997-01-04</datanascita>
    <num_maglia>3</num_maglia>
    <altezza>1.71</altezza>
    <market_value>20000000.00</market_value>
    <presenze>2</presenze>
    <cod_contratto>EJ0724</cod_contratto>
    <Tipo_Contratto>RINNOVATO</Tipo_Contratto>
    <stipendio>3700000.00</stipendio>
    <Data_inizio>2024-07-01</Data_inizio>
    <Data_scadenza>2028-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>11</ID>
    <cf>V1NW3SLEY</cf>
    <nome>Wesley Vinicius</nome>
    <cognome>Franca Lima</cognome>
    <nazionalita>Brasile</nazionalita>
    <datanascita>2003-09-06</datanascita>
    <num_maglia>43</num_maglia>
    <altezza>1.78</altezza>
    <market_value>20000000.00</market_value>
    <presenze>2</presenze>
    <cod_contratto>FW0725</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>3700000.00</stipendio>
    <Data_inizio>2025-07-28</Data_inizio>
    <Data_scadenza>2030-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>12</ID>
    <cf>R3N5CH</cf>
    <nome>Devyne</nome>
    <cognome>Rensch</cognome>
    <nazionalita>Olanda - Suriname</nazionalita>
    <datanascita>2003-01-18</datanascita>
    <num_maglia>2</num_maglia>
    <altezza>1.81</altezza>
    <market_value>10000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>RD0125</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>2220000.00</stipendio>
    <Data_inizio>2025-01-23</Data_inizio>
    <Data_scadenza>2029-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>13</ID>
    <cf>C3L1K</cf>
    <nome>Zeki</nome>
    <cognome>Celik</cognome>
    <nazionalita>Turchia</nazionalita>
    <datanascita>1997-02-17</datanascita>
    <num_maglia>19</num_maglia>
    <altezza>1.80</altezza>
    <market_value>6000000.00</market_value>
    <presenze>1</presenze>
    <cod_contratto>CZ0722</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>2560000.00</stipendio>
    <Data_inizio>2022-07-05</Data_inizio>
    <Data_scadenza>2026-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>14</ID>
    <cf>BRY4N</cf>
    <nome>Bryan</nome>
    <cognome>Cristante</cognome>
    <nazionalita>Italia - Canada</nazionalita>
    <datanascita>1995-03-03</datanascita>
    <num_maglia>4</num_maglia>
    <altezza>1.86</altezza>
    <market_value>7000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>CB0719</cod_contratto>
    <Tipo_Contratto>RINNOVATO</Tipo_Contratto>
    <stipendio>5190000.00</stipendio>
    <Data_inizio>2019-07-01</Data_inizio>
    <Data_scadenza>2027-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>15</ID>
    <cf>K0N3</cf>
    <nome>Manu</nome>
    <cognome>Kone</cognome>
    <nazionalita>Francia - Costa d'Avorio</nazionalita>
    <datanascita>2001-05-17</datanascita>
    <num_maglia>17</num_maglia>
    <altezza>1.85</altezza>
    <market_value>40000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>KM0824</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>5190000.00</stipendio>
    <Data_inizio>2024-08-30</Data_inizio>
    <Data_scadenza>2029-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>16</ID>
    <cf>N3IL0NE</cf>
    <nome>Neil</nome>
    <cognome>El Aynaoui</cognome>
    <nazionalita>Marocco - Francia</nazionalita>
    <datanascita>2001-07-02</datanascita>
    <num_maglia>8</num_maglia>
    <altezza>1.85</altezza>
    <market_value>15000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>EN0725</cod_contratto>
    <Tipo_Contratto>TRASFERIMENTO DEFINITIVO</Tipo_Contratto>
    <stipendio>2780000.00</stipendio>
    <Data_inizio>2025-07-20</Data_inizio>
    <Data_scadenza>2030-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>17</ID>
    <cf>P1S1LL1</cf>
    <nome>Niccolò</nome>
    <cognome>Pisilli</cognome>
    <nazionalita>Italia</nazionalita>
    <datanascita>2004-09-23</datanascita>
    <num_maglia>61</num_maglia>
    <altezza>1.80</altezza>
    <market_value>13000000.00</market_value>
    <presenze>0</presenze>
    <cod_contratto>PN0724</cod_contratto>
    <Tipo_Contratto>PROMOSSO DALLA PRIMAVERA</Tipo_Contratto>
    <stipendio>3330000.00</stipendio>
    <Data_inizio>2024-07-01</Data_inizio>
    <Data_scadenza>2029-06-30</Data_scadenza>
    <ID_utenti>1</ID_utenti>
  </giocatore>
  <giocatore>
    <ID>18</ID>
    <cf>B4LD4NZ1</cf>
    <nome>Tommaso</nome>
    <cognome>Baldanzi</cognome>
    <nazionalita>Italia</nazionalita>
    <datanascita>2003-03-23</datanascita>
    <num_maglia>35</num_maglia>
    <altezza>1.70</altezza>
    <market_value>12000000.00</market_value>
    <presenze>1</presenze>
