=== matteofiorentino03/LWEB-Homework3/xml/maglie_personalizzate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="maglie_personalizzate">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="maglia" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:int"/>
              <xs:element name="ID_Maglia" type="xs:int"/>
              <xs:element name="Logo" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="SERIE A"/>
                    <xs:enumeration value="CHAMPIONS LEAGUE"/>
                    <xs:enumeration value="EUROPA LEAGUE"/>
                    <xs:enumeration value="COPPA ITALIA"/>
                    <xs:enumeration value="CONFERENCE LEAGUE"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="supplemento" type="xs:int"/>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="num_maglia" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/maglie_personalizzate.xml
<?xml version="1.0" encoding="UTF-8"?>
<maglie_personalizzate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="maglie_personalizzate.xsd">
  <maglia>
    <ID>2</ID>
    <ID_Maglia>9</ID_Maglia>
    <supplemento>20</supplemento>
    <Logo>SERIE A</Logo>
    <nome>CAP</nome>
    <num_maglia>90</num_maglia>
  </maglia>
</maglie_personalizzate>
