=== matteofiorentino03/LWEB-Homework3/xml/maglie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="maglie">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="maglia" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:int"/>
              <xs:element name="tipo">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="casa"/>
                    <xs:enumeration value="fuori"/>
                    <xs:enumeration value="terza"/>
                    <xs:enumeration value="portiere"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="taglia">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="S"/>
                    <xs:enumeration value="M"/>
                    <xs:enumeration value="L"/>
                    <xs:enumeration value="XL"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Sponsor" type="xs:string" minOccurs="0"/>
              <xs:element name="stagione" type="xs:string"/>
              <xs:element name="descrizione_maglia" type="xs:string"/>
              <xs:element name="costo_fisso" type="xs:int"/>
              <xs:element name="path_immagine" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/maglie.xml
<?xml version="1.0" encoding="UTF-8"?>
<maglie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="maglie.xsd">
  <maglia>
    <ID>1</ID>
    <tipo>casa</tipo>
    <taglia>S</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>La nuova maglia da calcio della A.S. Roma per la stagione 2025/26 è rossa scura con i loghi e i bordi laterali arancioni.                   Questi colori ricordano la maglia del 1993-94, fatta da Adidas. Ufficialmente, i colori sono Claret/Arancione</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760345646_ebcf0f01.png</path_immagine>
  </maglia>
  <maglia>
    <ID>2</ID>
    <tipo>casa</tipo>
    <taglia>M</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>La nuova maglia da calcio della A.S. Roma per la stagione 2025/26 è rossa scura con i loghi e i bordi laterali arancioni.                     Questi colori ricordano la maglia del 1993-94, fatta da Adidas. Ufficialmente, i colori sono Claret/Arancione</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760345660_cb747c2e.png</path_immagine>
  </maglia>
  <maglia>
    <ID>3</ID>
    <tipo>casa</tipo>
    <taglia>L</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>La nuova maglia da calcio della A.S. Roma per la stagione 2025/26 è rossa scura con i loghi e i bordi laterali arancioni. Questi colori ricordano la maglia del 1993-94, fatta da Adidas. Ufficialmente, i colori sono Claret/Arancione</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760345668_4fc136a1.png</path_immagine>
  </maglia>
  <maglia>
    <ID>4</ID>
    <tipo>casa</tipo>
    <taglia>XL</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>La nuova maglia da calcio della A.S. Roma per la stagione 2025/26 è rossa scura con i loghi e i bordi laterali arancioni. Questi colori ricordano la maglia del 1993-94, fatta da Adidas. Ufficialmente, i colori sono Claret/Arancione</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760345691_4fd88a2d.png</path_immagine>
  </maglia>
  <maglia>
    <ID>5</ID>
    <tipo>fuori</tipo>
    <taglia>S</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>(Non c'è il logo di Riyadh Season)La maglia da calcio Adidas A.S. Roma 25-26 Fuori è di colore prevalentemente arancione, combinato con accenti neri e giallo brillante. Il logo Adidas, lo stemma del Lupetto, il colletto e le tre strisce sono tutti neri. La caratteristica più evidente della maglia è il motivo a fulmini che va dalla spalla sinistra alla parte inferiore destra della maglia, creando un look unico. Il motivo è ispirato all'antico mito di Giove.</descrizione_maglia>
    <costo_fisso>130</costo_fisso>
    <path_immagine>img/maglie/1760346273_33c807bd.png</path_immagine>
  </maglia>
  <maglia>
    <ID>6</ID>
    <tipo>fuori</tipo>
    <taglia>M</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>(Non c'è il logo di Riyadh Season)La maglia da calcio Adidas A.S. Roma 25-26 Fuori è di colore prevalentemente arancione, combinato con accenti neri e giallo brillante. Il logo Adidas, lo stemma del Lupetto, il colletto e le tre strisce sono tutti neri. La caratteristica più evidente della maglia è il motivo a fulmini che va dalla spalla sinistra alla parte inferiore destra della maglia, creando un look unico. Il motivo è ispirato all'antico mito di Giove.</descrizione_maglia>
    <costo_fisso>130</costo_fisso>
    <path_immagine>img/maglie/1760346280_3f249325.png</path_immagine>
  </maglia>
  <maglia>
    <ID>7</ID>
    <tipo>fuori</tipo>
    <taglia>L</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>(Non c'è il logo di Riyadh Season)La maglia da calcio Adidas A.S. Roma 25-26 Fuori è di colore prevalentemente arancione, combinato con accenti neri e giallo brillante. Il logo Adidas, lo stemma del Lupetto, il colletto e le tre strisce sono tutti neri. La caratteristica più evidente della maglia è il motivo a fulmini che va dalla spalla sinistra alla parte inferiore destra della maglia, creando un look unico. Il motivo è ispirato all'antico mito di Giove.</descrizione_maglia>
    <costo_fisso>130</costo_fisso>
    <path_immagine>img/maglie/1760346295_a8bc1a0f.png</path_immagine>
  </maglia>
  <maglia>
    <ID>8</ID>
    <tipo>fuori</tipo>
    <taglia>XL</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>(Non c'è il logo di Riyadh Season)La maglia da calcio Adidas A.S. Roma 25-26 Fuori è di colore prevalentemente arancione, combinato con accenti neri e giallo brillante. Il logo Adidas, lo stemma del Lupetto, il colletto e le tre strisce sono tutti neri. La caratteristica più evidente della maglia è il motivo a fulmini che va dalla spalla sinistra alla parte inferiore destra della maglia, creando un look unico. Il motivo è ispirato all'antico mito di Giove.</descrizione_maglia>
    <costo_fisso>130</costo_fisso>
    <path_immagine>img/maglie/1760346308_c54cda34.png</path_immagine>
  </maglia>
  <maglia>
    <ID>9</ID>
    <tipo>terza</tipo>
    <taglia>S</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Diventando una squadra d'elite Adidas a partire dalla stagione 25/26, la terza maglia sarà caratterizzata dal logo Trefoil. Per la prima volta nella storia, la terza maglia è bianca, abbinata ad accenti verdi e gialli e a un colletto a polo per un look classico.</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760346044_ab02cc83.png</path_immagine>
  </maglia>
  <maglia>
    <ID>10</ID>
    <tipo>terza</tipo>
    <taglia>M</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Diventando una squadra d'elite Adidas a partire dalla stagione 25/26, la terza maglia sarà caratterizzata dal logo Trefoil. Per la prima volta nella storia, la terza maglia è bianca, abbinata ad accenti verdi e gialli e a un colletto a polo per un look classico.</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760346054_0e5ea645.png</path_immagine>
  </maglia>
  <maglia>
    <ID>11</ID>
    <tipo>terza</tipo>
    <taglia>L</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Diventando una squadra d'elite Adidas a partire dalla stagione 25/26, la terza maglia sarà caratterizzata dal logo Trefoil. Per la prima volta nella storia, la terza maglia è bianca, abbinata ad accenti verdi e gialli e a un colletto a polo per un look classico.</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760346062_50d73b48.png</path_immagine>
  </maglia>
  <maglia>
    <ID>12</ID>
    <tipo>terza</tipo>
    <taglia>XL</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Diventando una squadra d'elite Adidas a partire dalla stagione 25/26, la terza maglia sarà caratterizzata dal logo Trefoil. Per la prima volta nella storia, la terza maglia è bianca, abbinata ad accenti verdi e gialli e a un colletto a polo per un look classico.</descrizione_maglia>
    <costo_fisso>150</costo_fisso>
    <path_immagine>img/maglie/1760346070_412d186b.png</path_immagine>
  </maglia>
  <maglia>
    <ID>13</ID>
    <tipo>portiere</tipo>
    <taglia>S</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Prima maglia da Portiere (non c'è il logo di Riyadh Season).</descrizione_maglia>
    <costo_fisso>120</costo_fisso>
    <path_immagine>img/maglie/1760346976_31fbbb9e.png</path_immagine>
  </maglia>
  <maglia>
    <ID>14</ID>
    <tipo>portiere</tipo>
    <taglia>M</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Prima maglia da Portiere (non c'è il logo di Riyadh Season).</descrizione_maglia>
    <costo_fisso>120</costo_fisso>
    <path_immagine>img/maglie/1760346984_e8a7c0d3.png</path_immagine>
  </maglia>
  <maglia>
    <ID>15</ID>
    <tipo>portiere</tipo>
    <taglia>L</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Prima maglia da Portiere (non c'è il logo di Riyadh Season).</descrizione_maglia>
    <costo_fisso>120</costo_fisso>
    <path_immagine>img/maglie/1760346992_4b799c1b.png</path_immagine>
  </maglia>
  <maglia>
    <ID>16</ID>
    <tipo>portiere</tipo>
    <taglia>XL</taglia>
    <Sponsor>Adidas</Sponsor>
    <stagione>2025/26</stagione>
    <descrizione_maglia>Prima maglia da Portiere (non c'è il logo di Riyadh Season).</descrizione_maglia>
    <costo_fisso>120</costo_fisso>
    <path_immagine>img/maglie/1760347010_ad41ec87.png</path_immagine>
  </maglia>
  <maglia>
    <ID>17</ID>
    <tipo>casa</tipo>
    <taglia>S</taglia>
    <Sponsor>Adidas, Riyadh Season</Sponsor>
    <stagione>2024/25</stagione>
    <descrizione_maglia>La maglia home dell'Adidas A.S. Roma 2024-25 presenta un'elegante combinazione di colori, con il colore principale Claret abbinato a loghi e linee verticali dorate</descrizione_maglia>
    <costo_fisso>100</costo_fisso>
    <path_immagine>img/maglie/1760347068_67bf64d3.png</path_immagine>
  </maglia>
  <maglia>
    <ID>18</ID>
    <tipo>casa</tipo>
    <taglia>M</taglia>
    <Sponsor>Adidas, Riyadh Season</Sponsor>
    <stagione>2024/25</stagione>
    <descrizione_maglia>La maglia home dell'Adidas A.S. Roma 2024-25 presenta un'elegante combinazione di colori, con il colore principale Claret abbinato a loghi e linee verticali dorate</descrizione_maglia>
    <costo_fisso>100</costo_fisso>
    <path_immagine>img/maglie/1760347079_4d1b9a59.png</path_immagine>
  </maglia>
  <maglia>
