=== matteofiorentino03/LWEB-Homework3/xml/maglie_giocatore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="maglie_giocatore">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="personalizzazione"  minOccurs="0"  maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:int"/>
              <xs:element name="Supplemento" type="xs:int"/>
              <xs:element name="Logo" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="SERIE A"/>
                    <xs:enumeration value="CHAMPIONS LEAGUE"/>
                    <xs:enumeration value="EUROPA LEAGUE"/>
                    <xs:enumeration value="COPPA ITALIA"/>
                    <xs:enumeration value="CONFERENCE LEAGUE"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="ID_Giocatore" type="xs:int"/>
              <xs:element name="ID_Maglia" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/maglie_giocatore.xml
<?xml version="1.0" encoding="UTF-8"?>
<maglie_giocatore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="maglie_giocatore.xsd">
  <personalizzazione>
    <ID>1</ID>
    <Supplemento>15</Supplemento>
    <Logo>SERIE A</Logo>
    <ID_Giocatore>18</ID_Giocatore>
    <ID_Maglia>9</ID_Maglia>
  </personalizzazione>
  <personalizzazione>
    <ID>3</ID>
    <Supplemento>15</Supplemento>
    <Logo>SERIE A</Logo>
    <ID_Giocatore>20</ID_Giocatore>
    <ID_Maglia>9</ID_Maglia>
  </personalizzazione>
  <personalizzazione>
    <ID>3</ID>
    <Supplemento>15</Supplemento>
    <Logo>CHAMPIONS LEAGUE</Logo>
    <ID_Giocatore>19</ID_Giocatore>
    <ID_Maglia>7</ID_Maglia>
  </personalizzazione>
</maglie_giocatore>
