=== matteofiorentino03/LWEB-Homework3/xml/portieri.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="portieri">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="portiere" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID_giocatore" type="xs:int"/>
              <xs:element name="gol_subiti" type="xs:int"/>
              <xs:element name="gol_fatti" type="xs:int"/>
              <xs:element name="assist" type="xs:int"/>
              <xs:element name="clean_sheet" type="xs:int"/>
              <xs:element name="ammonizioni" type="xs:int"/>
              <xs:element name="espulsioni" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/portieri.xml
<?xml version="1.0" encoding="UTF-8"?>
<portieri xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="portieri.xsd">
  <portiere>
    <ID_giocatore>1</ID_giocatore>
    <gol_subiti>3</gol_subiti>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <clean_sheet>2</clean_sheet>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
  </portiere>
  <portiere>
    <ID_giocatore>2</ID_giocatore>
    <gol_subiti>0</gol_subiti>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <clean_sheet>0</clean_sheet>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
  </portiere>
  <portiere>
    <ID_giocatore>3</ID_giocatore>
    <gol_subiti>0</gol_subiti>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <clean_sheet>0</clean_sheet>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
  </portiere>
  <portiere>
    <ID_giocatore>4</ID_giocatore>
    <gol_subiti>0</gol_subiti>
    <gol_fatti>0</gol_fatti>
    <assist>0</assist>
    <clean_sheet>0</clean_sheet>
    <ammonizioni>0</ammonizioni>
    <espulsioni>0</espulsioni>
  </portiere>
</portieri>
