=== matteofiorentino03/LWEB-Homework3/xml/sconti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Tipo enumerato per tutti i tipi di sconto -->
  <xs:simpleType name="TipoScontoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FEDELISSIMO"/>
      <xs:enumeration value="BENVENUTOLUPETTO"/>
      <xs:enumeration value="RETRO"/>
      <xs:enumeration value="REPUTAZIONE"/>
      <xs:enumeration value="ANZIANITA"/>
      <xs:enumeration value="TIPO_MAGLIA"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Tipo enumerato per maglia -->
  <xs:simpleType name="TipoMagliaType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CASA"/>
      <xs:enumeration value="FUORI"/>
      <xs:enumeration value="TERZA"/>
      <xs:enumeration value="PORTIERE"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Radice -->
  <xs:element name="sconti">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sconto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:int"/>
              <xs:element name="tipo" type="TipoScontoType"/>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="attivo" type="xs:boolean"/>
              <xs:element name="data_inizio" type="xs:date" minOccurs="0"/>
              <xs:element name="data_fine" type="xs:date" minOccurs="0"/>
              <xs:element name="percentualeFissa" type="xs:decimal" minOccurs="0"/>
              <xs:element name="percentualeMax" type="xs:decimal" minOccurs="0"/>
              <xs:element name="sogliaCreditiStep" type="xs:int" minOccurs="0"/>
              <xs:element name="patternCodice" type="xs:string" minOccurs="0"/>
              <!-- Condizioni opzionali -->
              <xs:element name="condizioniMaglia" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="stagione" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                    <xs:element name="tipo" type="TipoMagliaType" maxOccurs="3" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!-- Campi specifici reputazione -->
              <xs:element name="scontoReputazione" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="soglia" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="maxReputazione" type="xs:int"/>
                          <xs:element name="percentualeSconto" type="xs:decimal"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!-- Campi specifici anzianitÃ  -->
              <xs:element name="periodoMensilita" type="xs:decimal" minOccurs="0"/>
              <xs:element name="incrementoPercentuale" type="xs:decimal" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== matteofiorentino03/LWEB-Homework3/xml/sconti.xml
<?xml version="1.0" encoding="UTF-8"?>
<sconti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sconti.xsd">

  <!-- FEDELISSIMO -->
  <sconto>
    <ID>1</ID>
    <tipo>FEDELISSIMO</tipo>
    <nome>Sconto Fedelissimo 22%</nome>
    <attivo>true</attivo>
    <data_inizio>2023-01-01</data_inizio>
    <data_fine>2026-01-01</data_fine>
    <percentualeFissa>22</percentualeFissa>    
    <patternCodice>FEDELISSIMO22</patternCodice>
</sconto>

  <!-- BENVENUTOLUPETTO -->
  <sconto>
    <ID>2</ID>
    <tipo>BENVENUTOLUPETTO</tipo>
    <nome>Benvenuto Lupetto</nome>
    <attivo>true</attivo>
    <data_inizio>2023-01-01</data_inizio>
    <data_fine>2026-01-01</data_fine>
    <percentualeMax>30</percentualeMax>
    <patternCodice>^BENVENUTOLUPETTO([0-9]{1,2})$</patternCodice>
  </sconto>

  <!-- REPUTAZIONE -->
  <sconto>
    <ID>3</ID>
    <tipo>REPUTAZIONE</tipo>
    <nome>Sconto Reputazione</nome>
    <attivo>true</attivo>
    <data_inizio>2023-01-01</data_inizio>
    <data_fine>2026-01-01</data_fine>
    <scontoReputazione>
      
      
      
    <soglia><maxReputazione>30</maxReputazione><percentualeSconto>0</percentualeSconto></soglia><soglia><maxReputazione>70</maxReputazione><percentualeSconto>15</percentualeSconto></soglia><soglia><maxReputazione>100</maxReputazione><percentualeSconto>30</percentualeSconto></soglia></scontoReputazione>
  </sconto>

  <!-- ANZIANITA -->
  <sconto>
    <ID>4</ID>
    <tipo>ANZIANITA</tipo>
    <nome>Sconto Anzianit√†</nome>
    <attivo>true</attivo>
    <data_inizio>2023-01-01</data_inizio>
    <data_fine>2026-01-01</data_fine>
    <periodoMensilita>7</periodoMensilita>
    <incrementoPercentuale>3</incrementoPercentuale>
    <percentualeMax>30</percentualeMax>
  </sconto>

  <!-- TIPO_MAGLIA -->
  <sconto>
    <ID>5</ID>
    <tipo>TIPO_MAGLIA</tipo>
    <nome>Promo per Tipo Maglia</nome>
    <attivo>true</attivo>
    <data_inizio>2023-01-01</data_inizio>
    <data_fine>2026-01-01</data_fine>
    <percentualeFissa>30</percentualeFissa>
    <condizioniMaglia>
      <tipo>TERZA</tipo>
    </condizioniMaglia>
  </sconto>

  <!-- RETRO -->
  <sconto>
    <ID>6</ID>
    <tipo>RETRO</tipo>
    <nome>Sconto Retro 2001/02</nome>
    <attivo>true</attivo>
    <data_inizio>2023-01-01</data_inizio>
    <data_fine>2026-01-01</data_fine>
    <percentualeFissa>25</percentualeFissa>
    <condizioniMaglia>
      <stagione>2001/02</stagione>
      <tipo>CASA</tipo>
      <tipo>FUORI</tipo>
      <tipo>TERZA</tipo>
    </condizioniMaglia>
  </sconto>
</sconti>
